
name: .NET Core Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - uses: nuget/setup-nuget@v1

    #- name: Setup MSBuild.exe
    #  uses: microsoft/setup-msbuild@v1.0.0

    #- name: Nuget restore
    #  run: nuget restore Iridium360.Connect.Framework.Nuget/Iridium360.Connect.Framework.Nuget.csproj
      
    #- name: MSBuild
    #  run: msbuild Iridium360.Connect.Framework.Nuget/Iridium360.Connect.Framework.Nuget.csproj
    
    - name: Build
      run: dotnet msbuild Iridium360.Connect.Framework.Nuget/Iridium360.Connect.Framework.Nuget.csproj
      
    
