name: NUGET Iridium360.Connect.Framework

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    
    - id: nuget
      name: Build and publish NuGet
      run: |
          $PackageVersion = (Get-Content Iridium360.Connect.Framework.Nuget/Iridium360.Connect.Framework.Nuget.csproj | Select-String -Pattern '^\s*<Version>(.*)<\/Version>\s*$') -replace '<[^>]*>'
          
          echo $("Nuget generated name $PackageVersion")
          
          msbuild Iridium360.Connect.Framework.Nuget/Iridium360.Connect.Framework.Nuget.csproj `
            -t:Clean `
            -t:Rebuild `
            -t:Pack `
            -p:PackageVersion=$PackageVersion `
            -p:Configuration=Release
          
          $file = (dir "Iridium360.Connect.Framework.Nuget/bin/Release" -Filter *.nupkg | Sort-Object LastWriteTime -Desc | Select-Object -First 1)
          $path = $file.FullName 
          $name = $file.Name 
          
          dotnet nuget push $path --source "https://api.nuget.org/v3/index.json" --api-key $env:API_KEY
          
          echo $("::set-output name=path::$path")
          echo $("::set-output name=name::$name")
          
      shell: pwsh
      env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
          
          
    - name: 'Save build artifact'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.nuget.outputs.name }}
        path: ${{ steps.nuget.outputs.path }}
